apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  labels:
    app: frontend
    environment: production
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        environment: production
    spec:
      containers:
      - name: frontend
        image: nginx:latest